version: "3"
services:
  jupyter:
    build: .
    volumes:
      - ./:/kaggle
    working_dir: /kaggle/working
    ports:
      - 8080:8080
    command: jupyter notebook --port 8080 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    restart: always
